### PR TITLE
changed README.md

### PR DESCRIPTION
**Pull request by imyogeshgaur**

### CODE REVIEW

**Comment by AnkushSinghGandhi** [comment]
thanx for contributing

**Comment by AnkushSinghGandhi** [comment]
merging your pull request

**Comment by AnkushSinghGandhi** [comment]
show some love by following me on GitHub and starring some of my repositories

**Comment by imyogeshgaur** [comment]
Thank you @AnkushSinghGandhi for providing me the opportunity to contribute

**Pull request merged**
