### PR TITLE
adding my name to README

### PR DESCRIPTION
**Pull request by SABERGLOW**

### CODE REVIEW

**Comment by AnkushSinghGandhi** [comment]
how did you make your github profile header.

**Comment by SABERGLOW** [comment]
I made the wave animation in CodePen and then screen-recorded it, cut the recording and made a GIF out of it.
Here's a link to the pen: https://codepen.io/saberglow/pen/xxVwodW

**Comment by AnkushSinghGandhi** [comment]
i tried but i am not able to do it, 
can you do it for me

**Comment by SABERGLOW** [comment]
here: https://github.com/SABERGLOW/SABERGLOW/blob/master/Misc/AnkushSingh.gif

have fun, star my profile repo if it inspired u xD.

**Comment by AnkushSinghGandhi** [comment]
sure

**Pull request merged**
